default: single-network disjoint-network pub-priv-network

single-network:
	docker-compose -f single-network.yml up -d 

disjoint-network:
	docker-compose -f disjoint-network.yml up -d

pub-priv-network:
	docker-compose -f pub-priv-network.yml up -d
